#include "constants.h"


using namespace ragdoll;

char *bodyPartNames[BODYPART_COUNT] = { "BODYPART_PELVIS", "BODYPART_SPINE", "BODYPART_HEAD", "BODYPART_LEFT_UPPER_LEG",
"BODYPART_LEFT_LOWER_LEG", "BODYPART_RIGHT_UPPER_LEG", "BODYPART_RIGHT_LOWER_LEG",
"BODYPART_LEFT_UPPER_ARM", "BODYPART_LEFT_LOWER_ARM", "BODYPART_RIGHT_UPPER_ARM", "BODYPART_RIGHT_LOWER_ARM" };
